### ISSUE TITLE
CRITICAL (LOGIN): As a registered user, I want to be able to log in using my email address and password. In case I forgot my credentials, I want to be able to reset my account through the reset option on the login screen.

### ISSUE THREAD

**Issue by Slava-Berasneu** [sopra-fs22-group-15/cozycave-server#1]
- [x] sopra-fs22-group-15/cozycave-client#33
- [x] sopra-fs22-group-15/cozycave-client#32
- [x] https://github.com/sopra-fs22-group-15/cozycave-server/issues/90
- [ ] sopra-fs22-group-15/cozycave-server#25

**Comment by matthias-imhof** [comment]
independent development tasks:
- [ ] Create Class for Users
- [ ] Create REST API and Repository Endpoints
- [ ] Create Service Class for functionality and logic
- [ ] Create TestSuite
