### ISSUE TITLE
MAJOR (GOD MODE): As an administrator and moderator of the platform, I want to be able to remove and edit any ADs on the platform.

### ISSUE THREAD

**Issue by Slava-Berasneu** [sopra-fs22-group-15/cozycave-server#13]
- [x] sopra-fs22-group-15/cozycave-client#18
- [x] sopra-fs22-group-15/cozycave-client#17
- [x] sopra-fs22-group-15/cozycave-client#16
