### ISSUE TITLE
MINOR (FILTER&SORT ADS): As a user, I want to be able to filter the displayed ADs to the categories tailored to my interests

### ISSUE THREAD

**Issue by Slava-Berasneu** [sopra-fs22-group-15/cozycave-server#18]
- [x] sopra-fs22-group-15/cozycave-server#68
- [x] sopra-fs22-group-15/cozycave-client#6
- [x] sopra-fs22-group-15/cozycave-client#4
- [x] sopra-fs22-group-15/cozycave-client#3
