### ISSUE TITLE
CRITICAL (REGISTRATION): As a student of any Swiss university, I want to be able to sign up with my university email address and register myself for the service once I receive the verification code to my university email account. If registering using a non-student email, I want to be able to create an AD for a flat.

### ISSUE THREAD

**Issue by Slava-Berasneu** [sopra-fs22-group-15/cozycave-server#2]
- [ ] sopra-fs22-group-15/cozycave-server#26
- [x] sopra-fs22-group-15/cozycave-server#27
- [x] sopra-fs22-group-15/cozycave-client#31
- [x] https://github.com/sopra-fs22-group-15/cozycave-server/issues/90

**Comment by matthias-imhof** [comment]
- [ ] - Build logic to get university domains 
- [ ] - Sign-up as Student only possible with valid university domain
- [ ] - 
- [ ] - Send verification code to mail https://github.com/sopra-fs22-group-15/cozycave-server/issues/26

Complex TestSuite
- [ ] - Create an ad after signup
- [ ] - Apply for a flat without SignUp (should not be possible)
- [ ] - Apply for a flat with an account (but not a registered university domain) - (should not be possible)
- [ ] - Apply for a flat with a registerd and verified account
