### ISSUE TITLE
CRITICAL (PROPERTY BROWSING): As an unregistered user, I want to be able to use the landing page to browse the different properties listed on the website without having to sign up first

### ISSUE THREAD

**Issue by Slava-Berasneu** [sopra-fs22-group-15/cozycave-server#3]
- [x] sopra-fs22-group-15/cozycave-client#30
- [x] sopra-fs22-group-15/cozycave-server#31
- [x] https://github.com/sopra-fs22-group-15/cozycave-server/issues/89
- [x] sopra-fs22-group-15/cozycave-server#32

**Comment by matthias-imhof** [comment]
- [ ]  Create

**Comment by matthias-imhof** [comment]
https://github.com/sopra-fs22-group-15/cozycave-server/issues/89
