### ISSUE TITLE
CRITICAL (PHOTO UPLOADING): As a landlord, I want to be able to upload a main photo of the flat, the floor plan and additional photos to my AD, which are visible for anyone who clicks on the ad

### ISSUE THREAD

**Issue by Slava-Berasneu** [sopra-fs22-group-15/cozycave-server#4]
- [ ] sopra-fs22-group-15/cozycave-server#33
- [x] sopra-fs22-group-15/cozycave-client#29
- [ ] sopra-fs22-group-15/cozycave-client#28
