### ISSUE TITLE
User Implementation - independent development tasks

### ISSUE THREAD

**Issue by matthias-imhof** [sopra-fs22-group-15/cozycave-server#90]
independent development tasks:

- [x] - Create Class for User
- [x] - Create GET/PUT/POST Classes
- [x] - Create Mappers 
- [x] - Create REST API and Repository Endpoints
- [x] - https://github.com/sopra-fs22-group-15/cozycave-server/issues/91
- [x] - Add Table to Database

Create Service Class and implement:

- [x] - Create User (SIGN-UP)
- [x] - SIGN-IN 
- [x] - Remove User
- [x] - Return all Users
- [x] - Return single Listing
- [x] - Add https://github.com/sopra-fs22-group-15/cozycave-server/issues/91 to Users
- [ ] - Add multiple https://github.com/sopra-fs22-group-15/cozycave-server/issues/91 to Users
- [ ] - RESET Password
- [x] - Build logic to get university domains 
- [ ] - Sign-up as Student only possible with valid university domain
- [ ] - Send verification code to mail https://github.com/sopra-fs22-group-15/cozycave-server/issues/26

Complex TestSuite

- [ ]  - Test creation (Success / Fail)
- [ ] - Test SIGN-IN (Success / Fail)
- [ ]  - Test Reset Password (registerd, unregistered users)
- [ ] - Create an ad after signup
- [ ] - Apply for a flat without SignUp (should not be possible)
- [ ] - Apply for a flat with an account (but not a registered university domain) - (should not be possible)
- [ ] - Apply for a flat with a registerd and verified account
